const productData = {
    1: {
      name: "PP Dark Grey Granules",
      price: "₹78/Kg",
      description: "Dark Grey PP granules are ideal for automotive, industrial equipment, and consumer products.",
      orderQuantity:"200kg",
      specifications: {
        "Usage/Application": "General Plastics",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Packaging Type": "Loose",
        Purity: "100%",
        "Melting Point": "160 Degree C",
        Color: "Dark Grey",
      },
      images: [
        "https://5.imimg.com/data5/SELLER/Default/2024/8/446210081/SI/UG/TA/38167784/grey-pp-granules-500x500.jpg",
        "https://5.imimg.com/data5/SELLER/Default/2024/8/446774276/ME/IZ/CP/38167784/grey-pp-granules-500x500.png",
        "https://5.imimg.com/data5/SELLER/Default/2024/8/445904940/YS/KL/DF/38167784/photo-2024-08-26-18-15-31-jpg-500x500.jpg"
      ],
      link:"https://www.indiamart.com/ramashraykushwaha/our-products.html#2854736165162"
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      orderQuantity:"200kg",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    3: {
      name: "Green PP Natural Granules",
      price: "₹85/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      orderQuantity:"200kg",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Green",
      },
      images: [
        "https://5.imimg.com/data5/SELLER/Default/2024/8/446215645/MV/YE/RN/38167784/pp-natural-reprocessed-granules-500x500.jpg",
        "https://5.imimg.com/data5/SELLER/Default/2024/8/446215617/IH/EF/GR/38167784/pp-natural-reprocessed-granules-500x500.jpg",
        "https://5.imimg.com/data5/SELLER/Default/2024/8/446215647/FV/OK/TW/38167784/pp-natural-reprocessed-granules-500x500.jpg",
      ],
    },
    4: {
      name: "",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    3: {
      name: "PP Green Granules",
      price: "₹85/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
    2: {
      name: "Light Grey PP Natural Granules",
      price: "₹72/Kg",
      description: "Perfect for injection molding applications with high-quality natural PP material.",
      specifications: {
        "Usage/Application": "Injection Molding",
        "Types Of PP Granules": "Natural",
        Material: "Poly Propylene",
        Density: "0.92 g/cm3",
        "Melting Point": "160 Degree C",
        "Product Color": "Light Grey",
      },
      images: [
        "https://via.placeholder.com/400x300/aaaaaa",
        "https://via.placeholder.com/400x300/cccccc",
      ],
    },
  };
  
  export default productData;
  

  
